# Generated by Django 3.1.1 on 2020-09-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('contact', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('num_people', models.IntegerField()),
                ('reward', models.CharField(max_length=50)),
                ('condition', models.TextField()),
                ('detail', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('isUsed', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.content')),
            ],
        ),
    ]
