# Generated by Django 3.1.1 on 2020-09-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_content_num_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('num_student', models.CharField(max_length=50)),
                ('num_phone', models.CharField(max_length=50)),
                ('num_account', models.CharField(max_length=50)),
            ],
        ),
    ]
