# Generated by Django 3.1.1 on 2020-09-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_usertemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemp',
            name='password',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertemp',
            name='time_temp',
            field=models.OneToOneField(default=23421, on_delete=django.db.models.deletion.CASCADE, to='schedule.datetime'),
            preserve_default=False,
        ),
    ]
