# Generated by Django 3.1.1 on 2020-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200919_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetime',
            name='day_of_week',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
