# Generated by Django 3.1.1 on 2020-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_datetime_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='creator_key',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
    ]
